### PR TITLE
Fix callback-method setup using XmlDriver

### PR DESCRIPTION
**Pull request by curzio-della-santa**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Doc updated   | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/schmittjoh/serializer/issues/1311
| License       | MIT

### CODE REVIEW

**Comment by goetas** [comment]
Hi, thanks for your MR. Can you please rebase it and solve the merge conflicts (probably you've branched from an old branch).

Can you please also add a test for this change?

**Comment by curzio-della-santa** [comment]
Rebase done, for test it must wait that I find some spare time (really busy now)

**Comment by goetas** [comment]
i think that is worth fixing it anyway

**Comment by goetas** [comment]
thanks!

**Pull request merged**
