### PR TITLE
Added translation domain to FormErrorHandler

### PR DESCRIPTION
**Pull request by prosalov**
Added an ability to inject a translation domain parameter (validator.translation_domain) to FormErrorHndler. This is a solution suggestion for the following issue: https://github.com/schmittjoh/JMSSerializerBundle/issues/501

### CODE REVIEW

**Comment by goetas** [comment]
why not add an optional parameter to the constructor?

without tests, this can't be merged

**Comment by prosalov** [comment]
Injected translation domain param into the constructor and added tests. Please take a look.

**Comment by goetas** [comment]
looks good to me! thanks @prosalov!

**Comment by goetas** [comment]
can you update schmittjoh/JMSSerializerBundle#501 ?

**Pull request merged**
