### PR TITLE
Added deserialize type

### PR DESCRIPTION
**Pull request by bobvandevijver**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Doc updated   | yes
| BC breaks?    | no 
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | https://github.com/schmittjoh/JMSSerializerBundle/issues/582
| License       | Apache-2.0

This PR adds the possibility to have a different deserialization type than the original type. This can be useful for DateTime serialization, when you might expect an all zero time as result (see linked issue).

### CODE REVIEW

**Comment by goetas** [comment]
Sorry, did not manage to answer the in time, but will definitely prefer
just a third parameter for the date time... cant immagine a use case for
this feature

Will motivate properly on Monday


On 17 Jun 2017 19:08, "Bob van de Vijver" <notifications@github.com> wrote:

Q A
Bug fix? no
New feature? yes
Doc updated yes
BC breaks? no
Deprecations? no
Tests pass? yes
Fixed tickets schmittjoh/JMSSerializerBundle#582
<https://github.com/schmittjoh/JMSSerializerBundle/issues/582>
License Apache-2.0

This PR adds the possibility to have a different deserialization type than
the original type. This can be useful for DateTime serialization, when you
might expect an all zero time as result (see linked issue).
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/schmittjoh/serializer/pull/787
Commit Summary

   - Added deserialize type

File Changes

   - *M* doc/reference/annotations.rst
   <https://github.com/schmittjoh/serializer/pull/787/files#diff-0> (6)
   - *A* src/Annotation/DeserializeType.php
   <https://github.com/schmittjoh/serializer/pull/787/files#diff-1> (32)
   - *M* src/GenericDeserializationVisitor.php
   <https://github.com/schmittjoh/serializer/pull/787/files#diff-2> (6)
   - *M* src/Metadata/Driver/AnnotationDriver.php
   <https://github.com/schmittjoh/serializer/pull/787/files#diff-3> (3)
   - *M* src/Metadata/Driver/XmlDriver.php
   <https://github.com/schmittjoh/serializer/pull/787/files#diff-4> (7)
   - *M* src/Metadata/Driver/YamlDriver.php
   <https://github.com/schmittjoh/serializer/pull/787/files#diff-5> (4)
   - *M* src/Metadata/ExpressionPropertyMetadata.php
   <https://github.com/schmittjoh/serializer/pull/787/files#diff-6> (2)
   - *M* src/Metadata/PropertyMetadata.php
   <https://github.com/schmittjoh/serializer/pull/787/files#diff-7> (12)
   - *M* src/Metadata/StaticPropertyMetadata.php
   <https://github.com/schmittjoh/serializer/pull/787/files#diff-8> (2)
   - *M* src/Metadata/VirtualPropertyMetadata.php
   <https://github.com/schmittjoh/serializer/pull/787/files#diff-9> (2)
   - *M* src/XmlDeserializationVisitor.php
   <https://github.com/schmittjoh/serializer/pull/787/files#diff-10> (12)
   - *M* tests/Fixtures/BlogPost.php
   <https://github.com/schmittjoh/serializer/pull/787/files#diff-11> (9)
   - *M* tests/Metadata/Driver/BaseDriverTest.php
   <https://github.com/schmittjoh/serializer/pull/787/files#diff-12> (6)
   - *M* tests/Metadata/Driver/php/BlogPost.php
   <https://github.com/schmittjoh/serializer/pull/787/files#diff-13> (6)
   - *M* tests/Metadata/Driver/xml/BlogPost.xml
   <https://github.com/schmittjoh/serializer/pull/787/files#diff-14> (1)
   - *M* tests/Metadata/Driver/yml/BlogPost.yml
   <https://github.com/schmittjoh/serializer/pull/787/files#diff-15> (4)
   - *M* tests/Serializer/JsonSerializationTest.php
   <https://github.com/schmittjoh/serializer/pull/787/files#diff-16> (4)
   - *M* tests/Serializer/xml/blog_post.xml
   <https://github.com/schmittjoh/serializer/pull/787/files#diff-17> (2)
   - *M* tests/Serializer/xml/blog_post_unauthored.xml
   <https://github.com/schmittjoh/serializer/pull/787/files#diff-18> (2)
   - *M* tests/Serializer/yml/blog_post.yml
   <https://github.com/schmittjoh/serializer/pull/787/files#diff-19> (1)
   - *M* tests/Serializer/yml/blog_post_unauthored.yml
   <https://github.com/schmittjoh/serializer/pull/787/files#diff-20> (1)

Patch Links:

   - https://github.com/schmittjoh/serializer/pull/787.patch
   - https://github.com/schmittjoh/serializer/pull/787.diff

—

**Comment by bobvandevijver** [comment]
Right 😅 

Well, luckily I also created the other solution! However, I do think there can be some usecases.. For example, when you want to deserialize a child member a a special class which indicates the deserialization step. Might be far fetched though.

**Comment by goetas** [comment]
closing in favor of https://github.com/schmittjoh/serializer/pull/788

**Comment by goetas** [comment]
> Will motivate properly on Monday

so, the main reason that what this PR was trying to solve was a "format" issue, not a type.  objects have a type, and that type is "serialized" in a certain format. 

Dates to be serialized or parsed back to objects have 10.000 different formats (standards... https://imgs.xkcd.com/comics/iso_8601.png).
Different "formats" will converge to a class `DateTime` (hopefully always...)

**Comment by martintama** [comment]
Hi, I might have a use case that might be suitable for this PR. I consume an API that returns a full object in one property, (so I use the @Type("ObjectType") annotation), but it expects a string when patching that property (which is the field "name" belonging to that object). 

I tried changing the getter of this property to return not the object itself but the property value, but I always get the following error: 

`
[Symfony\Component\Debug\Exception\ContextErrorException]
Warning: ReflectionProperty::getValue() expects parameter 1 to be object, string given
`

So what I'm doing as a workaround this is kind of a hack. I assign a non-existent `@Group` to that field, to prevent it from being serialized back, and then add a new getter with the `@VirtualProperty` and `@SerializedName` annotations that just returns the property name.

The final result looks like this:

```php
/**
 * Client
 *
 */
class Client
{
    /**
     * @var int
     * @Serializer\Type("integer")
     *
     */
    private $id;

    /**
     * @var Country
     * @Serializer\Type("AppBundle\Entity\Country")
     * @Serializer\Groups({"excluded"})
     */
    private $country;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set country
     *
     * @param string $country
     * @return Client
     */
    public function setCountry($country)
    {
        $this->country = $country;

        return $this;
    }

    /**
     * Get country
     *
     * @return Country
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * @Serializer\VirtualProperty
     * @Serializer\SerializedName("country")
     */
    public function getCountryName(){
        if ($this->getCountry()){
            return $this->getCountry()->getName();
        }
    }

}
```

Is there any other cleaner way to achieve this? Having a Hi, I have a use case that might be suitable for this PR. I consume an API that returns a full object in one property, (so I use the @Type("ObjectType") annotation), but it expects a string when patching that property (which is the field "name" belonging to that object). 

I tried changing the getter of this property to return not the object itself but the property value, but I always get the following error: 

`
[Symfony\Component\Debug\Exception\ContextErrorException]
Warning: ReflectionProperty::getValue() expects parameter 1 to be object, string given
`

So what I'm doing as a workaround this is kind of a hack. I assign a non-existent `@Group` to that field, to prevent it from being serialized back, and then add a new getter with the `@VirtualProperty` and `@SerializedName` annotations that just returns the property name.

The final result looks like this:

```php
/**
 * Client
 *
 */
class Client
{
    /**
     * @var int
     * @Serializer\Type("integer")
     *
     */
    private $id;

    /**
     * @var Country
     * @Serializer\Type("AppBundle\Entity\Country")
     * @Serializer\Groups({"excluded"})
     */
    private $country;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set country
     *
     * @param string $country
     * @return Client
     */
    public function setCountry($country)
    {
        $this->country = $country;

        return $this;
    }

    /**
     * Get country
     *
     * @return Country
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * @Serializer\VirtualProperty
     * @Serializer\SerializedName("country")
     */
    public function getCountryName(){
        if ($this->getCountry()){
            return $this->getCountry()->getName();
        }
    }

}
```

Is there any other cleaner way to achieve this? Having a `@DeserializeType("string")` might help in this situation.

**Comment by goetas** [comment]
I tend to use symfony/form when is about handling requests that involve any kind of data validation or normalization.

I use almost always jms/serializer when serializing, while the deserialization component is used only when the incoming data do not require validation or normalization.

If the data are different, shouldn't you use DTOs?

**Pull request closed without merging**
