### PR TITLE
Can now override groups on specific paths of the graph

### PR DESCRIPTION
**Pull request by adrienbrault**
This is backward compatible, and pretty awesome IMHO :heart_eyes:

Inspired from one of the examples on #150

### CODE REVIEW

**Comment by lopsided** [comment]
+1 This is great. Will this work with yml mapping files too?

**Comment by smilesrg** [comment]
+1 for this!

**Comment by Seb33300** [comment]
Any news about this?
Will it be merged?

**Comment by fadamsen** [comment]
I was looking for a way to do exactly this, so +1 from me as well.

**Comment by dvitharanage** [comment]
+1 need this feature for large object graphs of related entities. It should be possible to override child object groups from the parent property. Why isn't this merged yet????

**Comment by goetas** [comment]
Finally this is on master

**Pull request merged**
