### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by Soullivaneuh**
As I said on https://github.com/schmittjoh/serializer/pull/510#issuecomment-149468264, there is some failing tests on master.

This PR fixes them.

BTW, you should configure Travis with the repository to prevent it on the future.

### CODE REVIEW

**Comment by stof** [comment]
Travis is running. It is simply not reporting the commit status because of an outdated token. See #495

**Comment by Soullivaneuh** [comment]
> It is simply not reporting the commit

Yeah, this is what I want to say. ;-)

**Comment by TiS** [comment]
As for fixing doctype tests, I have referenced this in https://github.com/schmittjoh/serializer/pull/508 . I thought it was deliberate that doctypes work using full <!DOCTYPE string (to maintain backwards compatibility), so "corrected" the function instead of tests.

**Comment by Soullivaneuh** [comment]
Nice @TiS. Ping me when your PR will be merged, I'll update mine. :+1:

**Comment by TiS** [comment]
I'm not sure, if my solution is better than yours ;) But *if* project owner decides so, I'll let you know.

**Comment by Soullivaneuh** [comment]
ping @schmittjoh

**Comment by localheinz** [comment]
@schmittjoh 

Can we merge this to make the build pass?

Also see #526.

**Comment by goetas** [comment]
this is probably outdated now

**Comment by goetas** [comment]
Closing, tests are already green. If some features are missing, please re open a new PR

**Comment by localheinz** [comment]
@goetas 

It's probably outdated because nobody has taken care of it.

**Comment by goetas** [comment]
@localheinz , i started right today as  maintainer of this project, hope in the future PRs will have a shorter feedback loop

**Comment by localheinz** [comment]
@goetas

:+1:

**Pull request closed without merging**
