### PR TITLE
Fix deprecated assertFileNotExist

### PR DESCRIPTION
**Pull request by mpoiriert**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Doc updated   | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #... 
| License       | MIT

### CODE REVIEW

**Comment by goetas** [comment]
I think that you should increase the minimum required version of phpunit, as some builds are failing

**Comment by mpoiriert** [comment]
Yes you are right. I have remove 7 since it reach it's end of support

**Comment by mpoiriert** [comment]
So it's not compatible with PHPUnit 8.0 either.

Do you want me to remove it ? If there is no need to have a older version require dev. PHPUnit 8 is compatible with php 7.2 so it should be ok.

**Comment by goetas** [comment]
I think that removing phpunit 7 is ok, regarding your changes, unfortunately I think that we have to postpone them

**Comment by mpoiriert** [comment]
There is always a way.

I did that so we don't have the deprecated warning, it's a temporary fix.

**Comment by goetas** [comment]
nice! thanks!

**Pull request merged**
