### PR TITLE
Serialize null in positional arrays

### LINKED ISSUE #571: Invalid null serialization in arrays
This code 
https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/GenericSerializationVisitor.php#L104-L106

```php
            if (null === $v && ( ! is_string($k) || ! $context->shouldSerializeNull())) {
                continue;
            }
```

Test
```php
$context = \JMS\Serializer\SerializationContext::create();
$context->setSerializeNull(true);
var_dump($serializer->toArray([1, null, 2], $context));

$context = \JMS\Serializer\SerializationContext::create();
$context->setSerializeNull(true);
var_dump($serializer->serialize([1, null, 2], 'json', $context));
```

Output
```
array(2) {
  [0] =>
  int(1)
  [2] =>
  int(2)
}

string(13) "{"0":1,"2":2}"
```

Dropping null value makes the `json_encode` think of the data like the named properties. I think correct condition should be

if (null == $v && is_string($k) && !$context->shouldSerializeNull()) {
   continue;
}

In this case we drop null only in case they are at hash array, not positional.

### PR DESCRIPTION
**Pull request by scaytrase**
Fix #571

### CODE REVIEW

**Comment by scaytrase** [comment]
I'm ready to fix some related tests but I'm not sure which failures belong to the patch as the whole build history is red
https://travis-ci.org/schmittjoh/serializer/builds

**Comment by maennchen** [comment]
@scaytrase You can now reabse on the original master and everything should get green.

**Comment by scaytrase** [comment]
Thanks, all green.

**Comment by scaytrase** [comment]
The given commit actually does not resolve the problem.

It fails a simple test

```php
    public function testNullArraySerialization()
    {
        $array = [0, null, 'a'];
        self::assertSame($array, $this->serializer->toArray($array));
    }
```

How we force an array being normalized as array, not object?

**Pull request closed without merging**
