### PR TITLE
softened prefix check effectively forcing prefix for default namespace

### PR DESCRIPTION
**Pull request by maZahaca**

### CODE REVIEW

**Comment by schmittjoh** [comment]
Could you add a test for what this is doing?

**Comment by discordier** [comment]
I guess he wants the default namespace prefix (which is the first one in `$registeredNamespaces`) enforced on ALL elements which is plain wrong IMO as by doing so, he is removing the possibility to set an `xsi:schemaLocation` or `xsi:noNamespaceSchemaLocation` from an listener which is needed in some cases. Every element will get prefixed with the just created prefix.
This change also seems to create a new namespace prefix alias for the default namespace on every element which is definately not a wise idea.

**Comment by maZahaca** [comment]
I cannot add tests, because that commit was added by another developer, but anyway that fix works for me

**Comment by goetas** [comment]
Sorry for the terribly long feedback loop

Closing the PR, since too many things changed on master in the last years. If you are still interested in working on this feel free to re-open a new PR based on the current master including proper tests

**Pull request closed without merging**
