### PR TITLE
Drop Travis

### PR DESCRIPTION
**Pull request by simPod**

### CODE REVIEW

**Review by peter279k — APPROVED** [review]

**Comment by gam6itko** [comment]
I am afraid that the build of docs has been broken. I don't see any replacement of `.travis/install_docs.sh` and `.travis/script_docs.sh` files

**Comment by simPod** [comment]
@gam6itko thanks, did not notice it. Will do.

**Comment by simPod** [comment]
CI failures are fixed in #1327

**Comment by simPod** [comment]
@goetas Hi, I've been trying to keep this up to date for some time but would be nice if we could merge this so people contributing to the lib would need to change Github actions config instead of Travis' one so I don't have to do it then. Thanks!

**Comment by goetas** [comment]
Hi, I'm sorry , I forgot about this. Now is merged

**Comment by simPod** [comment]
Nice! Ping me if there are any issues.

**Pull request merged**
