### PR TITLE
[new] implementing https://github.com/schmittjoh/serializer/issues/537

### PR DESCRIPTION
**Pull request by dbojdo**

### CODE REVIEW

**Comment by alcalyn** [comment]
Just the interface I was looking for, +1

**Comment by alcalyn** [comment]
Now you may want to remove phpdoc block (or set `{@InheritDoc}`) on `fromArray` and `toArray` methods to avoid to duplicate doc

**Comment by alcalyn** [comment]
I reintegrated this PR to have green tests: https://github.com/schmittjoh/serializer/pull/592

**Comment by goetas** [comment]
Sorry for the terribly long feedback loop

Closing the PR, since too many things changed on master in the last years and there is a newer implementation in #592. If you are still interested in working on this feel free to re-open a new PR based on the current master.

**Pull request closed without merging**
