### PR TITLE
Rebase of serialization nesting onto the latest

### PR DESCRIPTION
**Pull request by bassrock**
This is a rebase of #341 on the latest code base. It also adds some accessor methods to remove properties via a callback after it has been serialized.

### CODE REVIEW

**Comment by digitalkaoz** [comment]
+1

**Comment by crisu83** [comment]
+1 as we use the same instance for serialization across our Lumen application through DI.

**Comment by bassrock** [comment]
@schmittjoh Any chance of merging this in? Just rebased with the latest from master again.

**Comment by bassrock** [comment]
@goetas Since you look to be helping now. Any chance of merging this in?

**Comment by goetas** [comment]
I see some problems with this PR that makes it "not reday to be merged". First, you have removed tests. Second,  this approach complicates all the visitors  adding code to handle this specific usecase. 

Have you considered an approach of recreating only the visitor instance for each seralization call? It should give that same result without changing visitors code...

**Comment by bassrock** [comment]
@goetas Im not sure what you mean when you say I removed tests. I haven't removed any tests. 

How would you recreate the visitor instance for each serialization call?

**Comment by goetas** [comment]
>  Im not sure what you mean when you say I removed tests. I haven't removed any tests.

as you can see on https://github.com/schmittjoh/serializer/pull/453/files there are no tests

> How would you recreate the visitor instance for each serialization call?

https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/Serializer.php#L68 contains the list of visitors.

Currently visitors are pre-instantiated in the serialization builder. Doing some kind of lazy-instantiation/callback  will allow to instantiate the visitor right when needed.

It is a bit more complex feature, but is a general solution to the problem exposed here

**Comment by goetas** [comment]
Nested serialization calls currently require big changes, for a relatively small benefit. Probably getting a new serializer instance can partially fix the issue.

Not planning to accept the feature for now.

**Pull request closed without merging**
