### PR TITLE
Non-locale aware encoding of doubles, closes #1041

### LINKED ISSUE #1041: Values of type "double" should not use locale-specific encoding
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

## Steps required to reproduce the problem

1. Use locale with decimal separator other than dot, e.g. `setlocale(LC_ALL, 'ru_RU.UTF-8')`
2. Try to serialize value of type double with fractional part, e.g. 1.234

## Expected Result

* Value should be encoded in using fixed format: no thousands separator, dot as fractional separator, e.g. "1.234"

## Actual Result

* Value encoded in locale-aware way, with locale-specific settings, e.g. "1,234", which will lead to parsing errors on produced serialized file.

This behaviour caused by converting double values to string type by using (string) operator:
```
    public function visitDouble($data, array $type, Context $context)
    {
        ...
            return $this->document->createTextNode((string) $data);
        ...
```
Easiest way to convert double to machine-readable string is using json_encode: `json_encode((double)$data)`

### PR DESCRIPTION
**Pull request by Grundik**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Doc updated   | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #1041 
| License       | MIT

### CODE REVIEW

**Comment by goetas** [comment]
not sure if JSON encode is the best tool for the job here. 

has anybody a better idea?

@Grundik can you crate a test case for this?

**Comment by Grundik** [comment]
I've added tests. Strictly speaking, existing tests already failing on systems with inconvenient system locale. Its only a matter of default locale.

json_encode exports float value as string in machine-readable form without losing precision. Its the simplest way of accomplishment of such task. Another way could be switching to C locale, but that could cause severe performance degradation.

**Comment by goetas** [comment]
What about this https://3v4l.org/WgoZh ? (does not require json)

**Comment by Grundik** [comment]
Thats better, and does not requires integer hack. I've made changes to PR.

But: var_exports works good on floats only on PHP >= 7.0.2, so backporting this bugfix to older versions should be done via json_encode, if that would be done.

**Comment by goetas** [comment]
This package requires php ^7.2 so it should not be a probelm

**Comment by Grundik** [comment]
We encountered this bug in 5.6, and we have so stick to this version for now, so I have backported this fix to 1.13.0 (https://github.com/Grundik/serializer/commits/bugfix-1041-1.13.0 if you're interested).

**Comment by goetas** [comment]
Thanks!

**Pull request merged**
