### PR TITLE
added @required annotation as well as tests

### PR DESCRIPTION
**Pull request by michaelrios**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Doc updated   | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | Apache-2.0

### CODE REVIEW

**Comment by mjgorman** [comment]
+1

**Comment by goetas** [comment]
Hi. Thanks for the PR! 
Quick question: why do not use a validator as symfony/validator?

**Comment by michaelrios** [comment]
This just fits what I need, and without adding any overhead to existing processes. I also do not need any other features in the symfony/validator package, so that would add a bit more bloat to my application.

**Comment by goetas** [comment]
Hi @michaelrios thanks again for the PR. 
Unfortunately can not accept the PR (even from the code point of view looks good).

This serializer library focuses on serialization/deserialization; normalization and validation are sometimes overlapping tasks, but IMO fundamentally different (and already well covered by way better alternatives as symfony form or symfony validator).

**Pull request closed without merging**
