### PR TITLE
add options property to XmlDeserializationVisitorFactory and XmlDeserializationVisitor, propagate defined value from factory to simplexml_load_string call

### PR DESCRIPTION
**Pull request by kopeckyales**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Doc updated   | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #828
| License       | MIT

### CODE REVIEW

**Comment by goetas** [comment]
Hi!
This looks a pretty nice thing to have! Thanks!

Do you mind adding some tests for it?

**Comment by kopeckyales** [comment]
Hi goetas, thank you for quick response.
For me, only option how to test this is something similar to this: [php_mock_global_functions_for_unit_tests_with_phpunit](http://marcelog.github.io/articles/php_mock_global_functions_for_unit_tests_with_phpunit.html)
But it is like 50/50 because this approach seems strange for me.

I was thinking about "mock" the simplexml_load_string function and save given options parameter to the global value and then in test check if options parameter was propagated correctly.
This is IMHO bulletproof test, but as I said, I do not really like the approach.

If you are satisfied with mentioned solution, I can implement it.

**Comment by goetas** [comment]
Instead of mocking the behavior of simplexml_load_string, you can try to pass some option to the visitor, then call 'prepare', and check if the return of it followed the $options rules

**Comment by kopeckyales** [comment]
Of course, your solution is possible, but in my opinion it is not suitable test. What if simplexml_load_string changes in future and will return different result for whatever reason? It breaks the test even if nothing in your code was changed. And of course it do not guarantee if all options are propagated correctly, just the one you are testing. For me, this is almost comparable to have no test and it is the reason why i searched for something more bullet-proof. I only found given solution.

**Comment by goetas** [comment]
I think we can keep it as it is. 
Nor happy with both solutions. :/ but would like to have this feature

**Pull request merged**
