### PR TITLE
Fix Doctrine PHPCR ODM 2.0 compatibility

### PR DESCRIPTION
**Pull request by wouterj**
This available since PHPCR ODM 1.1 and the old method is removed in 2.0.

### CODE REVIEW

**Comment by goetas** [comment]
As i can see, https://github.com/doctrine/phpcr-odm/tree/2.0  is not yet tagged

**Comment by goetas** [comment]
i guess you should change composer.json too

**Comment by goetas** [comment]
@wouterj ping

**Comment by wouterj** [comment]
> As i can see, https://github.com/doctrine/phpcr-odm/tree/2.0 is not yet tagged (released)

Indeed. But as the `doctrine/phpcr-odm` is a dev requirement, this package can be installed with PHPCR ODM 2.0-dev. This case is currently broken (and is holding up development of CMF 2.0 / PHPCR 2.0, as we rely on JMS serializer).

Updated the `composer.json` file.

**Comment by wouterj** [comment]
Btw, cool to see some development progress in this repository again! :)

**Comment by goetas** [comment]
:+1: 
looks good

**Comment by wouterj** [comment]
Thanks!

Op vr 12 aug. 2016 22:04 schreef Asmir Mustafic <notifications@github.com>:

**Pull request merged**
