### PR TITLE
Disabling accessor setter when value resolution falls back to the property default value

### PR DESCRIPTION
**Pull request by joaojacome**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Doc updated   | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #1421 
| License       | MIT

### CODE REVIEW

**Comment by joaojacome** [comment]
@goetas @scyzoryck please review :)

**Review by scyzoryck — APPROVED** [review]
@joaojacome Thanks for contribution! Do you think that it cause no breaking changes? Should we update documentation for this behavior? 

Best, Marcin

**Comment by joaojacome** [comment]
@goetas Can you take a look at this one?

Thanks!

**Comment by goetas** [comment]
@joaojacome  hi, I will! sorry for the delay

**Comment by annervisser** [comment]
@goetas any chance you could tag a release? We are currently unable to upgrade beyond 3.17.1 and this PR fixes that

**Pull request merged**
