### PR TITLE
#367 Exclude annotation not preventing attempt to find public methods when using AccessType

### PR DESCRIPTION
**Pull request by Strate**
Attempt to find getters and setters only if property included to serialization.

### CODE REVIEW

**Comment by mattjanssen** [comment]
:+1: I was just about to create this exact PR.

When using `@AccessType("public_method")` the call to `setAccessor()` fails for properties that don't have a setter/getter. This is regardless of `@Exclude` or `@ExclusionPolicy("ALL")` annotations.

The exception thrown is:
```
There is no public %s method in class %s. Please specify which public method should be used for setting the value of the property %s.
```

**Comment by mattjanssen** [comment]
Issue #367

**Comment by sagikazarmark** [comment]
What's blocking this from being merged? IMO this is a serious issue needs to be addressed ASAP.

**Comment by goetas** [comment]
looks good to me

**Comment by goetas** [comment]
checked again, looks good. Thank you

**Pull request merged**
