### PR TITLE
for issue 216

### PR DESCRIPTION
**Pull request by brettminnie**
Added in test logic to see if we have an object before we try set the property directly

### CODE REVIEW

**Comment by nuxwin** [comment]
We got the exact same issue during our tests but not for the very same scenario.

Let's imagine the following ; We have a client which sends an entity to our backend for update. Now let imagine that the user changed the identifier manually in the payload (json). Well, when we deserialize the payload, we get the same error:

```
Warning: ReflectionProperty::setValue() expects parameter 1 to be object, null given in /var/cache/imscp/packages/vendor/jms/serializer/src/JMS/Serializer/GenericDeserializationVisitor.php on line 176

Fatal error: Call to a member function setstatus() on a non-object in /var/cache/imscp/packages/vendor/jms/serializer/src/JMS/Serializer/GenericDeserializationVisitor.php on line 181
```

This problem occurs only when we use the **DoctrineObjectConstructor** which is needed for us because we use Doctrine. What we expect in place is an **EntityNotFoundException** such as:

```
Entity of type 'iMSCP\ApsStandard\Entity\ApsInstance' for IDs id(3) was not found
```

that would come from the merge attempt of an inexistent entity. For instance:

```php
/** @var EntityManager $entityManager */
$entityManager = Registry::get('ServiceLocator')->get('EntityManager');
/** @var Serializer $serializer */
$serializer = Registry::get('ServiceLocator')->get('Serializer');
/** @var ApsPackageService $apsPackageService */
$apsPackageService = Registry::get('ServiceLocator')->get('ApsPackageService');

$instance = (new ApsInstance())
	->setStatus('ok');

$payload = $serializer->serialize($instance, 'json');

# Mimic client payload modification
$ob = json_decode($payload);
$ob->id = 3;

$payload = json_encode($ob);

$instance = $serializer->deserialize($payload, 'iMSCP\ApsStandard\Entity\ApsInstance', 'json'); Here, no error should occurs.
$mergedInstance = $entityManager->merge($apsInstance); // Here we must get an EntityNotFoundException Exception
```

To get this behavior, we added the following code part in the **DoctrineObjectConstructor** like this:

```php
...
        // Entity update, load it from database
        $object = $objectManager->find($metadata->name, $identifierList);

        if(null === $object) { // Added code part
                return $this->fallbackConstructor->construct($visitor, $metadata, $data, $type, $context);
        }
...
```

**Comment by nuxwin** [comment]
@brettminnie 

I'm not sure but I think that your way to fix the problem is not good. Your fix would result to no exception when the entity doesn't exists (eg, a new managed entity would be created without identifier). This would lead to some problems such as creation of new entity even for an update action. On update action, we expect the process to fail with an **EntityNotFoundException**.

**Comment by mmeloni** [comment]
Same problem.
 It works adding  the following code part in the DoctrineObjectConstructor (tnx @nuxwin ):
if(null === $object) { // Added code part
                return $this->fallbackConstructor->construct($visitor, $metadata, $data, $type, $context);
        }

We can hope in a patch or we have to fork?

**Comment by goetas** [comment]
Sorry for the terribly long feedback loop

Closing the PR, since too many things changed on master in the last years. If you are still interested in working on this feel free to re-open a new PR based on the current master including proper tests

(Solved probably with https://github.com/schmittjoh/serializer/pull/550)

**Pull request closed without merging**
