### PR TITLE
Allow to use custom serializer with primitive type

### PR DESCRIPTION
**Pull request by goetas**
This patch will allow to create custom handles for primitive types (strings for example)

(i use it make translations during serialization)

### CODE REVIEW

**Comment by holtkamp** [comment]
+1, using the XSD2PHP functionality of @goetas, automation of (de)serialization of big object hierarchies becomes quite important when dealing with subjects like:

- [OpenTravel Association](http://schemas.liquid-technologies.com/OpenTravel/2008B/)
- Single European Payment Area (SEPA), which use [ISO20022 XML Schemas](https://github.com/w2c/sepa-sdd-xml-generator/blob/master/validation_schemes/)
- [iDEAL Payments](https://github.com/juriansluiman/SlmIdealPayment/blob/master/data/xsd/AcceptantAcquirer.xsd)
- [Seamless Seqr Payments](http://developer.seqr.com/merchant/reference/api.html)

Sometimes XML signing / base encoding, or other transformations are needed during (de)serialization, so more flexibility would be nice.

**Comment by hiend** [comment]
+1

**Comment by holtkamp** [comment]
@schmittjoh please consider reopening this, here is an example of a SimpleType that would be useful to have a Custom Handler dealing with:

https://github.com/juriansluiman/SlmIdealPayment/blob/master/data/xsd/AcceptantAcquirer.xsd#L394-L398

Ok, the ```type: DateTime<"Y-m-d\TH:i:s.u\Z">``` can be used, but a CustomHandler would provide more flexibility.

**Comment by goetas** [comment]
Rebased again.
@schmittjoh Please consider reopening this. There are many use cases for this feature

**Comment by goetas** [comment]
@schmi
> This use-case is not common enough that I want to add more ifs to the code base and I'm also not really sure that the serializer is the right layer for these transformations (at least the current architecture was not designed for this).

please re-consider this, is already a long time that some people (a lot) are requesting this feature. some example are https://github.com/schmittjoh/serializer/pull/507 https://github.com/goetas-webservices/xsd2php-runtime/pull/1 https://github.com/AuthorizeNet/sdk-php/issues/146 https://github.com/AuthorizeNet/sdk-php/issues/73 and probably many other.

the feature is BC and does not introduce a high amount of logic

**Comment by aramalipoor** [comment]
:+1:

**Comment by schmittjoh** [comment]
@goetas it's not so much about the amount of code required, but about the performance impact. Most of the types we handle are primitive types, and moving them through the event system/handler system will severely impact performance. Did you benchmark this?

**Comment by goetas** [comment]
@schmittjoh 
The approach used in this PR has no real performance impact. The reason is that is still not possible to register an event handler for a type `string`, so no event managers are triggered.

To use a custom mapping on this PR is necessary to declare a custom type.  Example: 

```php
class Author {
    /**
     * @Type("MyNonExistentClass")
     * @var string
     */
    private $name; // is a string
}
```

The type of `$name` is `string`, but `@Type` annotation declares something different (in this case `MyNonExistentClass`. This allows to register an handler for `MyNonExistentClass` and to process it.

This has no general performance impact, and the serialization of the type `string` is not affected. 
To be even more clear, will still be not possible to register custom handlers for `@Type("string")` declarations.


I have also tried a general approach in https://github.com/goetas/serializer/pull/3, allowing to have custom handlers for `@Type("string")` definitions, and that created a 20% penality (using `tests/benchmark.php` benchmark). 
This PR is way simpler, and there are not real performance changes.

**Comment by schmittjoh** [comment]
Ah sorry, I was looking at that other PR yesterday before reading the comments here.

Could you fix the coding-style (indentation) so we can merge this. I also cannot re-open this PR because GitHub says there is already one open. Did you create another one?

**Comment by goetas** [comment]
Ok, will rebase and create a new one!

**Comment by goetas** [comment]
https://github.com/schmittjoh/serializer/pull/610 rebased version of this

**Comment by goetas** [comment]
:tada:

**Comment by goetas** [comment]
@schmittjoh thank you!

**Comment by holtkamp** [comment]
Great, @goetas this means https://github.com/goetas/xsd2php does not rely on a patched version of the Serializer anymore?

**Comment by goetas** [comment]
not yet :(  there were few more commits that were not yet published as PR here... working on it. One of them is https://github.com/schmittjoh/serializer/pull/611 , but probably two more are coming

**Comment by holtkamp** [comment]
Aah, ok, well, kudos for your perseverance 😄

**Pull request closed without merging**
