### PR TITLE
Allow doctrine/lexer 2

### PR DESCRIPTION
**Pull request by derrabus**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Doc updated   | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT

This PR allows the installation of `doctrine/lexer` 2.x.

### CODE REVIEW

**Review by scyzoryck — COMMENTED** [review]
Thanks for contribution! 
@goetas could you run CI tests to see if we have any tests that will use that package?

**Comment by goetas** [comment]
hmm, that is weird. can't understand why phpstan fails...

**Comment by derrabus** [comment]
> hmm, that is weird. can't understand why phpstan fails...

Because you're referencing a class from the doctrine/cache package that has been removed in version 2. This is unrelated to my change and can be observed on the master branch as well.

**Comment by derrabus** [comment]
My attempt to fix the PHPStan failure: #1447.

**Comment by goetas** [comment]
Thanks @derrabus ! really appreciated!

**Pull request merged**
