### PR TITLE
add / discriminator for classes in the middle of hierarchy

### PR DESCRIPTION
**Pull request by scasei**

### CODE REVIEW

**Comment by scasei** [comment]
what do i have to do to get this pull request merged?

maybe its also a solution for this never ending issue: https://github.com/schmittjoh/JMSSerializerBundle/issues/292

**Comment by larsborn** [comment]
I created the following minimal example: 

    <?php
    require 'vendor/autoload.php';
    use Doctrine\Common\Annotations\AnnotationRegistry;
    
    AnnotationRegistry::registerAutoloadNamespace('JMS\Serializer\Annotation', __DIR__ . '/src');
    
    abstract class MovingObject
    {
    }
    
    /**
     * @JMS\Serializer\Annotation\Discriminator(field = "type", map = {"car": "Car", "moped": "Moped"})
     */
    abstract class Vehicle extends MovingObject
    {
    }
    
    class Car extends Vehicle
    {
    }
    
    class Moped extends Vehicle
    {
    }
    
    $data = [new Car(), new Moped()];
    
    $serializer = JMS\Serializer\SerializerBuilder::create()->build();
    
    $serialized = $serializer->serialize($data, 'xml');
    var_dump($serialized);
    $deserialized = $serializer->deserialize($serialized, 'array<Vehicle>', 'xml');
    var_dump($deserialized);
    var_dump($deserialized == $data);


which fails with the following error: `PHP Fatal error:  Uncaught exception 'Doctrine\Instantiator\Exception\InvalidArgumentException' with message 'The provided class "Vehicle" is abstract, and can not be instantiated'`. Adding the above lines solves the problem. What do you need in addition to merge this PR?

**Comment by larsborn** [comment]
we needed this urgently, so we forked and created a new release: https://github.com/simplethings/serializer/releases/tag/0.13.1

thanks to everyone involved!

**Comment by RuslanZavacky** [comment]
@larsborn @schmittjoh any chances to fix tests and merge it?

**Comment by larsborn** [comment]
Hi @RuslanZavacky, the tests where broken even before this PR afair. We merged the fix on the fork https://github.com/simplethings/serializer. So, if you also need it, just use tag 0.13.1 or apply the patch to the version you would like to use in the fork (PRs are welcome ;-)).

**Comment by ouniamani** [comment]
i need  advice
An exception occurred while executing 'INSERT INTO user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, discr) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, 0, "jkam2e7fclc04cwsws4wgk0ogg8ggos", null, null, 0, 0, null, null, null, "a:0:{}", 0, null, "administrateur"]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Le champ 'username' ne peut être vide (null)

**Comment by goetas** [comment]
Sorry for the terribly long feedback loop

Closing the PR, since too many things changed on master in the last years. If you are still interested in working on this feel free to re-open a new PR based on the current master including proper tests

**Pull request closed without merging**
