### PR TITLE
Discriminator Groups

### PR DESCRIPTION
**Pull request by maennchen**
Fix for Issue schmittjoh/JMSSerializerBundle#506

### CODE REVIEW

**Comment by schmittjoh** [comment]
Could you add tests?

**Comment by maennchen** [comment]
Yes. Could you by any chance merge the PR #511 that my tests could have a chance to pass?

**Comment by maennchen** [comment]
@schmittjoh Tests are done.

**Comment by maennchen** [comment]
@schmittjoh: I'm going to apply it on my own fork since you're obviously not interested in maintaining this lib anymore.

**Comment by wins1908** [comment]
@maennchen Could you add your branch again? I need your branch too
@schmittjoh Could you accept @maennchen merge request?

**Comment by maennchen** [comment]
I waited long enough. Feel free to merge jms-serializer/serializer back into the official repo.

**Comment by maennchen** [comment]
You can install the fork by running this command:

```bash
composer require "jms-serializer/serializer"
```

It will replace the original lib.

**Comment by schmittjoh** [comment]
@maennchen, sorry for the wait, would you mind re-basing the discriminator commit and adjusting the serialize/unserialize method so that it is BC by either throwing an exception or setting a default value? It looks good otherwise.

**Pull request closed without merging**
