### PR TITLE
Add throws tag

### PR DESCRIPTION
**Pull request by VincentLanglet**
Hi @goetas 

Your implementation of this interface is throwing Runtime exceptions, so it should be good to add the `@throws` tag to the interface ; this way the developer is aware to catch them.

### CODE REVIEW

**Comment by VincentLanglet** [comment]
I don't think the scrutinizer error is related to my PR.

Are you interested @goetas ? :)

**Comment by goetas** [comment]
TBH I do not know.

PHP (contrary to Java) does not force you to catch the declared exceptions, so do not see really a value in declaring them.

It would just make a lot of noise, and it we want to be strict we would have to place hundreds of `@throw SomeException`  all over the code

**Comment by VincentLanglet** [comment]
Hi

> PHP (contrary to Java) does not force you to catch the declared exceptions, so do not see really a value in declaring them.

To me, it's like saying (when we were in php5)
> PHP does not force you to respect `@param` and `@return` so do not see really value declaring them.

PHP does not force you, but some static analysis like phpstan/psalm can help you to report uncaught exceptions. But only if they are declared in the phpdoc, of course. 

I got an error in production because I didn't catch the exception, and nothing helps me to know they were an exception to catch. This would have avoid such error. 

> It would just make a lot of noise

Why noise ? Phpdoc is documentation
As an example, symfony interfaces have `@throws` tags: https://github.com/symfony/contracts/search?q=throws

> it we want to be strict we would have to place hundreds of @throw SomeException all over the code

Yes, maybe. But if so, that does mean that currently, people are using method which can throws exception without knowing it ! That's seems to be a risky thing.

People shouldn't wait to get an exception to know they have to catch something.

**Comment by goetas** [comment]
Anyway I think that this will now hurt, so it is ok.

**Comment by VincentLanglet** [comment]
Thanks

**Comment by VincentLanglet** [comment]
Does a 3.11.1 release would be possible ? @goetas :)

**Pull request merged**
