### PR TITLE
Issue543 - Added support for DateTimeImmutable

### PR DESCRIPTION
**Pull request by toby-griffiths**
Duplicated DateTime related tests & amended to DateTimeImmutable.

All 'datetime' group tests passing with this update

### CODE REVIEW

**Comment by toby-griffiths** [comment]
Not sure why this is failing on the composer install, as I've not changed any composer elements.

**Comment by goetas** [comment]
looks good. any chance to rebase it? (there are some merge conflicts...)

and, question: what is the reason behind having `serializeDateTime`, serializeDateTimeImmutable` and `serializeDateTimeInterface`, and all of them as public methods...

probably everything should work with just `serializeDateTimeInterface`... is because of BC compatiblity or is there something else?

**Comment by toby-griffiths** [comment]
I'll try to get round to rebasing this soon, but I've got a very busy couple of weeks ahead of me, so likely to be after that's all done.

**Comment by toby-griffiths** [comment]
Oops.  I didn't mean to close this issue, but my branch needed rebasing so was out of line with the new rebased branch.
I'll submit a new PR now.
If I could have done this a better way, someone please let me know.

**Comment by toby-griffiths** [comment]
Raised new PR for rebased branch (https://github.com/schmittjoh/serializer/pull/635)

**Pull request closed without merging**
