### PR TITLE
Remove ReadOnly since jms serializer cannot be used with PHP 8.1 projects with it

### PR DESCRIPTION
**Pull request by simPod**
I'm performing full codebase scan and php8.1 cannot parse it now with this class being present

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| Doc updated   | no
| BC breaks?    | yes (already specified in UPGRADING)
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | #... 
| License       | MIT

### CODE REVIEW

**Comment by simPod** [comment]
See https://github.com/schmittjoh/serializer/runs/5023529751?check_suite_focus=true for failure

**Comment by goetas** [comment]
why that ? i'm using jms with php 8.1 and symfony 5.4. what is blocking you from using it on php 8.1? do you get some error?

**Comment by simPod** [comment]
Yes, that's because you're not scanning your code base entirely, thus not hitting read-only class. Simply try to load Readonly.php on Php81. The problem is sole presence of the class there.

**Comment by simPod** [comment]
E.g. this https://github.com/maglnet/ComposerRequireChecker <https://github.com/maglnet/ComposerRequireChecker> or whatever else that does the same kind of actions. The class must not exist in PHP 8.1 projects.

**Comment by mbabker** [comment]
This is the same discussion as https://github.com/schmittjoh/serializer/issues/1381

**Comment by simPod** [comment]
Closing in favor of https://github.com/schmittjoh/serializer/pull/1405

**Pull request closed without merging**
