### PR TITLE
use Twig 2.7 namespaces

### PR DESCRIPTION
**Pull request by IonBazan**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Doc updated   | no
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT

Twig 2.7 moved to namespaced classes instead of old pre-PHP5.3 ones.

### CODE REVIEW

**Comment by IonBazan** [comment]
I think there is a problem with Travis-CI config - the test is shown as passed, but it contains errors: https://travis-ci.org/schmittjoh/serializer/jobs/506178733. Although, it's not caused by this PR.

**Comment by goetas** [comment]
Hi, Thanks for the PR.

Currently I think that is not a good idea to drop Twig 1.x and <2.7 support. C

Can this changes be done in a backward compatible way, preferring the new class names if they are available, and falling back on the old if they are not available?

**Comment by enumag** [comment]
This doesn't necessarily break compatibility with all versions <2.7. Namespaced aliases existed several versions before that, 2.7 only added the deprecation of non-namespaced types.

Btw. not supporting Twig 2.7 is quite a problem now because roave/security-advisories no longer allows Twig 2.0-2.6 because of this [vulnerability](https://symfony.com/blog/twig-sandbox-information-disclosure).

**Comment by mbabker** [comment]
> Can this changes be done in a backward compatible way, preferring the new class names if they are available, and falling back on the old if they are not available?

If the version constraint is set to `~1.34|~2.4` then you're OK, those were the two releases where the namespaced aliases were introduced.

**Comment by goetas** [comment]
Having `~1.34|~2.4` is ok for me

**Comment by goetas** [comment]
Thanks!

**Pull request merged**
