### PR TITLE
Symfony 5.0 compatibility

### PR DESCRIPTION
**Pull request by goetas**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Doc updated   | no
| BC breaks?    | -
| Deprecations? | -
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT

### CODE REVIEW

**Comment by Bukashk0zzz** [comment]
@goetas Hi, When you plan to merge this PR?

**Comment by goetas** [comment]
was waiting for someone to review it...

**Comment by Bukashk0zzz** [comment]
I know that I am not the one who can say for sure that all cool, but as for me all looks right.

I tested this brunch on my Symfony 5 project using composer aliasing:
```
"jms/serializer": "sf5-dev as 3.3.x-dev",
"jms/serializer-bundle": "^3.5",
```

All works well. Before these fixes, I get an error about TranslatorInterface when serializing Symfony form.

**Comment by goetas** [comment]
Alright! Thanks for checking

**Comment by goetas** [comment]
Will create a new tag tomorrow

**Comment by Bukashk0zzz** [comment]
Thank you.

**Pull request merged**
