### PR TITLE
Add Context for translateName in PropertyNamingStrategyInterface

### PR DESCRIPTION
**Pull request by LeaklessGfy**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Doc updated   | no
| BC breaks?    | yes/no 
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | #857 
| License       | Apache-2.0

### CODE REVIEW

**Comment by goetas** [comment]
Sorry but this cant be merged. Adding a parameter in a public method is a BC break change

**Comment by goetas** [comment]
While a new interface is just a new feature

**Comment by LeaklessGfy** [comment]
Got it ! Will work on that with a new interface

**Comment by LeaklessGfy** [comment]
I close this one since it doesn't fit the requirements.

**Pull request closed without merging**
