### PR TITLE
Serialize float with precision, dec_point and thousands separator

### PR DESCRIPTION
**Pull request by anuri73**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Doc updated   | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | no
| Fixed tickets | #636
| License       | MIT

It's not best solution, but it's work

### CODE REVIEW

**Comment by goetas** [comment]
Well, a json float does not allow "thousands separator" and the "dec_point" must be ".".

What you are trying to do here is to convert to string a float using some localized representation.

**Comment by anuri73** [comment]
Sorry, didn't check well. It was made in haste. Give another chance for this issue

**Comment by anuri73** [comment]
Can you please help,  where I can store properties for number_format. Is it ok, if I declare the numberFormatDecimals, numberFormatDecPoint and numbgerFormatThousandsSep properties in the JsonSerializationVisitor itself?

**Comment by goetas** [comment]
if you need to make sure that `float 2.0` is always converted to `2.0` you can use the already available `JSON_PRESERVE_ZERO_FRACTION` option for the json visitor.

If you want to use numbgerFormatThousandsSep and numberFormatDecPoint and other stuff, then you are not dealing with a float but with a string. to do so you can use a custom type.

Something as 

```php

 /** @Type("MyFormattedFloat<'', '.', ' '>") */
 public $val = 12.3145
```

and adding a custom type handler for the `MyFormattedFloat` type

**Pull request closed without merging**
