### PR TITLE
document how to make annotations autoloadable

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by greg0ire** [comment]
ping @schmittjoh

**Comment by greg0ire** [comment]
Yearly ping @schmittjoh

**Comment by schmittjoh** [comment]
I'm not sure whether we need to document how annotations work. Is there not something in the Doctrine docs?

**Comment by greg0ire** [comment]
Yes there is (and I linked to it in my PR), but this kind of problem keeps repeating over and over and people sometimes struggle to find the solution. It bears repeating IMO.

**Comment by greg0ire** [comment]
Of course, this is just my opinion, feel free to close this PR if you feel otherwise.

**Comment by greg0ire** [comment]
ping @schmittjoh : again, if by "I'm not sure", you mean "this is useless IMO", just close the PR, I don't have any problem with that.

**Comment by greg0ire** [comment]
ping @schmittjoh

**Comment by goetas** [comment]
Not a big improvements, plus each framework now days loads annotations in its own way. as example in symfony 
```php
AnnotationRegistry::registerLoader(array($loader, 'loadClass'));
```

**Comment by greg0ire** [comment]
TIL several things : 

- small improvements are not worth merging
- not using a framework / using a framework that does not provide some kind of plugin for this library means you have to figure that kind of thing by yourself

**Comment by greg0ire** [comment]
But let's not kid myself this isn't going to get merged so let's agree to disagree. Closing.

**Pull request closed without merging**
