### PR TITLE
Add support for `list<T>`

### PR DESCRIPTION
**Pull request by simPod**
| Q             | A
| ------------- | ---
| Bug fix?      |no
| New feature?  | yes
| Doc updated   | yes
| BC breaks?    | no 
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | #... 
| License       | MIT

- [ ] not sure I've tested that on proper places

### CODE REVIEW

**Comment by simPod** [comment]
List implies numeric and sequenced keys starting from 0. Array<T> has whatever keys of array-key. See https://php.watch/versions/8.1/array_is_list for explanation e. g.

**Comment by goetas** [comment]
in jms `array<T>`  is exactly a list. what is not a list has to be expressed as `array<string,T>`

**Comment by simPod** [comment]
> in jms array<T> is exactly a list

In that case this should be deprecated as it does not comply with current typesystem adopted by ecosystem (phpstan, psalm, IDEs, ...)

-------------

This PR adds support for `@param list<int>` so no additional jms serializer annotations are required for that. I'll add a fixture with that.

**Comment by dborsatto** [comment]
Hey @goetas I've got the same issue with the serializer, the `list<T>` annotation has become the standard for this kind of meaning, so annotating with `array<T>` to make the serializer work breaks other tools as technically `array<T>` is only a parent type of `list<T>` (the Psalm [docs](https://psalm.dev/docs/annotating_code/type_syntax/array_types/) explain this quite nicely).

Is there any way I can help with this PR? :slightly_smiling_face:

**Comment by goetas** [comment]
ok, since this seems on demand, let put it in core

**Pull request merged**
