### PR TITLE
Allow multiple nested serializer calls

### PR DESCRIPTION
**Pull request by xavierlacot**
In case of serializer recursion, the serializer send an exception: "Can't pop from an empty datastructure", as noted by @damienalexandre in #319 

This PR allows to stack the navigator association to visitors, thus making it possible to nest serializer calls. It contains two commits:
- the first one contains the required changes for the bug to be fixed;
- the second one adds a test which shows up the bug resolution (tested against the fixed testsuite proposed in #292)

### CODE REVIEW

**Comment by ogizanagi** [comment]
Any news about this PR ?

**Comment by schmittjoh** [comment]
I'm not sure whether we need to support this use-case, i.e. nested calls. I think it might be better to create another serializer instance if you need this instead of using the same instance.

**Comment by ogizanagi** [comment]
Thanks for the quick answer :smiley: 

This could be out of the scope of the current debate, but may I ask you the proper way to do that, as I need to register my custom handlers too, in the context of a Symfony 2 application ?
This basically means redoing the same work as in the `jms/serializer-bundle`, right ?

However, for my use case, using the `SerializerBuilder` directly, and registering the handlers I need seems sufficient.

**Comment by damienalexandre** [comment]
I find it disturbing that we need a fresh new `Serializer` to perform nested calls. A new `SerializationContext` should be enough. I use `Serializer` as a service most of the time, where one instance is supposed to fit all serialization needs.

Isn't it like saying `Serializer` is not stateless?

**Comment by digitalkaoz** [comment]
yeah ran into the same issue here...sadly the serializer is somewhat stateless and thats a bad design here in my eyes

**Comment by digitalkaoz** [comment]
@schmittjoh why are you blocking this valid use case?

**Comment by digitalkaoz** [comment]
if you have a more complex serializer construction (custom handlers, event subscribers, object constructor etcpp) this is a pain in the ass.

**Comment by bassrock** [comment]
:+1:

**Comment by bassrock** [comment]
@schmittjoh this helps especially when using this with Symfony so that you can reuse the injected serializer in different parts of the same code run.

**Comment by bassrock** [comment]
I created a new branch that mimics this but on the latest code base with a few additions. #453

**Comment by sfavot** [comment]
:+1:

**Comment by goetas** [comment]
Do not know if this is still an issue,  but https://github.com/schmittjoh/serializer/pull/453#issuecomment-237467700 proposes an alternative implementation for this feature

**Comment by goetas** [comment]
Nested serialization calls currently require big changes, for a relatively small benefit. Probably getting a new serializer instance can partially fix the issue.

Not planning to accept the feature for now.

**Comment by xavierlacot** [comment]
So this makes the serializer stateful and unusable as a service, with all the performance and memory consumption downsides.

This is a blocker for "real life" production usage, as explained in the previous comments. This has proven to be blocking in at least 3 or 4 of our client projects, and should be clearly stated in the documentation: "jms-serializer is stateful and doesn't care of performance issues".

**Comment by patie** [comment]
👍

**Pull request closed without merging**
