### PR TITLE
Update Symfony validator and allow PHPUnit 7

### PR DESCRIPTION
**Pull request by goetas**
- allow phpunit 5.0 and 4.0
- allow sf validator ^2.2

### CODE REVIEW

**Comment by goetas** [comment]
@stof i tired to allow the SF 3.0 validation api. ATM I suggest to postpone it since is not a trivial change

**Comment by goetas** [comment]
@schmittjoh i guess the exception has been fixed,  is it? still have to understand scrutinizer :)

**Comment by stof** [comment]
@goetas right

**Comment by schmittjoh** [comment]
Guess I missed this pull-request :)

**Pull request merged**
