### PR TITLE
Remove hoa compiler

### PR DESCRIPTION
**Pull request by Jean85**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Doc updated   | no
| BC breaks?    | no
| Deprecations? | yes 
| Tests pass?   | no
| Fixed tickets | #1182
| License       | MIT

This is a draft for replacing Hoa dependencies with the Doctrine Lexer.

### CODE REVIEW

**Comment by goetas** [comment]
Woha! thats nice!

**Comment by mantis** [comment]
nice

**Comment by Jean85** [comment]
Sorry for not pushing this forward, I'm actually low on available time, and I don't know where to start understanding Doctrine's lexer. Feel free to take my work and push it forward!

**Comment by goetas** [comment]
Moving conversation to https://github.com/schmittjoh/serializer/pull/1212

**Pull request closed without merging**
