### PR TITLE
Added support for an "array" format

### PR DESCRIPTION
**Pull request by tystr**
This PR adds support for an "array" format, providing the functionality to serialize to and deserialize from arrays.

### CODE REVIEW

**Comment by renan** [comment]
:+1:

**Comment by rdohms** [comment]
@schmittjoh can we please get this merged and working? Its been over 2 years from a simple format. I can't see any reason left to not merge this.

**Comment by schmittjoh** [comment]
Alright, while I do not like the approach with the separate "array" format as explained above, I'd like to propose a different approach:

- add separate methods for converting to/from arrays/objects: ``toArray()``/``fromArray()``
- re-use the implementation of ``serialize()``/``deserialize()`` with the JSON-visitor hard-coded and instead of calling ``getResult`` use the ``getRoot`` method for serialization, and for deserialization just omit calling ``prepare``

If someone can provide a patch with a few tests, then I'll happily merge that.

**Comment by schmittjoh** [comment]
Closing this in favor of the new PR.

**Comment by davidwindell** [comment]
To all those subscribed to this, the new PR has now been merged into master with #435

**Pull request closed without merging**
