### PR TITLE
Allow root null

### PR DESCRIPTION
**Pull request by umpirsky**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | yes
| Doc updated   | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | https://github.com/schmittjoh/JMSSerializerBundle/issues/788
| License       | MIT

### CODE REVIEW

**Comment by goetas** [comment]
Nice! thanks! can you please add some tests for it?

**Comment by umpirsky** [comment]
Where are `SerializationGraphNavigator` tests?

**Comment by umpirsky** [comment]
I can't install deps and can't run tests locally:

```
composer install -v
Deprecation Notice: The behavior of unparenthesized expressions containing both '.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence in phar:///usr/local/bin/composer/src/Composer/Downloader/SvnDownloader.php:132
Stack trace:
 phar:///usr/local/bin/composer/vendor/composer/ClassLoader.php:322
 phar:///usr/local/bin/composer/src/Composer/Factory.php:483
 phar:///usr/local/bin/composer/src/Composer/Factory.php:360
 phar:///usr/local/bin/composer/src/Composer/Factory.php:576
 phar:///usr/local/bin/composer/src/Composer/Console/Application.php:332
 phar:///usr/local/bin/composer/src/Composer/Console/Application.php:444
 phar:///usr/local/bin/composer/src/Composer/Console/Application.php:149
 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:127
 phar:///usr/local/bin/composer/src/Composer/Console/Application.php:100
 phar:///usr/local/bin/composer/bin/composer:54
 /usr/local/bin/composer:24
Loading composer repositories with package information
Updating dependencies (including require-dev)

                                                                                           
  [ErrorException]                                                                         
  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?  
                                                                                           

Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleSetGenerator.php:286
 Composer\Util\ErrorHandler::handle() at phar:///usr/local/bin/composer/vendor/composer/ClassLoader.php:444
 include() at phar:///usr/local/bin/composer/vendor/composer/ClassLoader.php:444
 Composer\Autoload\includeFile() at phar:///usr/local/bin/composer/vendor/composer/ClassLoader.php:322
 Composer\Autoload\ClassLoader->loadClass() at n/a:n/a
 spl_autoload_call() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php:75
 Composer\DependencyResolver\Solver->__construct() at phar:///usr/local/bin/composer/src/Composer/Installer.php:470
 Composer\Installer->doInstall() at phar:///usr/local/bin/composer/src/Composer/Installer.php:226
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php:119
 Composer\Command\InstallCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:266
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:861
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:208
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:245
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:127
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:100
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:54
 require() at /usr/local/bin/composer:24

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

```

**Comment by goetas** [comment]
I think that you are using an old version of composer, please update it

**Comment by umpirsky** [comment]
You are right, updated helped. Thanks.

I added tests.

**Comment by umpirsky** [comment]
@goetas Is it good to go now?

**Comment by goetas** [comment]
i've merged a slightly improved version of it in https://github.com/schmittjoh/serializer/pull/1250 (this was not working as expected with xml)

**Comment by umpirsky** [comment]
Thanks @goetas in what version/when can we expect this to be released?

**Comment by umpirsky** [comment]
@goetas ?

**Pull request closed without merging**
