### PR TITLE
Bugfix: arrays returned as objects like {"0":... }

### PR DESCRIPTION
**Pull request by Nadrieril**
Tests added https://github.com/schmittjoh/serializer/pull/304

### CODE REVIEW

**Comment by dizda** [comment]
What's up on this PR?

**Comment by hairmare** [comment]
:+1:

**Comment by narcoticfresh** [comment]
+1

**Comment by andreaslarssen** [comment]
Is this actually a fix for THE bug? Anyone maintaining this repo still?

**Comment by dizda** [comment]
Have you tried with the last release of this repo? Seems the last commits fixed this pb on my projects.

**Comment by andreaslarssen** [comment]
You're ABSOLUTELY right. Composer update did it. Thanks! My bad, but should this PR be closed, and along with it all the issues related to it?

**Comment by dizda** [comment]
Agree to close this issue :+1: .

**Pull request closed without merging**
