### PR TITLE
[docs] Add documentation to deserialize on existing objects

### PR DESCRIPTION
**Pull request by gam6itko**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| Doc updated   | yes
| BC breaks?    | no 
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | #978
| License       | MIT

### CODE REVIEW

**Comment by goetas** [comment]
Nice! thanks!

**Comment by yosvield** [comment]
How is the best way to deserialize on existing objects, i do not find in the documentation

**Comment by gam6itko** [comment]
@yosvield http://jmsyst.com/libs/serializer/master/cookbook/object_constructor#deserialize-on-existing-objects

**Comment by yosvield** [comment]
@gam6itko Thank you

**Comment by grekpg** [comment]
i still dont understand how to do it .... 
You should pass ExistingObjectConstructor to DeserializationGraphNavigatorFactory constructor. ?? how ?
im using SymfonyBundle

**Pull request merged**
