### PR TITLE
Added custom depth handling for circular references

### PR DESCRIPTION
**Pull request by brettminnie**
This is my solution to allowing recursion to happen deeper than the default depth

### CODE REVIEW

**Comment by brettminnie** [comment]
Rebased against master

**Comment by goetas** [comment]
Sorry for the terribly long feedback loop

Closing the PR, since too many things changed on master in the last years. If you are still interested in working on this feel free to re-open a new PR based on the current master.

**Comment by brettminnie** [comment]
Many thanks,

Are you now helping maintain the repository?

**Comment by goetas** [comment]
> Are you now helping maintain the repository?

started last week

**Pull request closed without merging**
