### PR TITLE
[WIP] add AllGroups Option

### PR DESCRIPTION
**Pull request by mgiustiniani**
I added AllGroups directive.

I use this library with serializerGroups options in all my entities, this feature have a limitation when i use external libraries because i need to rewrite some code of these libraries. i open a issue in Hateoas-php for this problem https://github.com/willdurand/Hateoas/issues/141

- [ ]  added xml driver
- [ ]  added test case
- [ ]  added docs
- [ ]  gather feedback

### CODE REVIEW

**Comment by mrcmorales** [comment]
ping

**Comment by adrienbrault** [comment]
@mgiustiniani Can you describe how you plan to use this AllGroups annotation ?

**Comment by mgiustiniani** [comment]
in my idea allGroups is used for bypass, for certain fields, a group serialization check
my first example is this library https://github.com/djlambert/doctrine2-spatial. these object can't serialized if i use groups in my representation.

**Comment by goetas** [comment]
Sorry for the terribly long feedback loop

Closing the PR, since too many things changed on master in the last years. If you are still interested in working on this feel free to re-open a new PR based on the current master.

**Pull request closed without merging**
