### PR TITLE
Add integer alias to docs.

### PR DESCRIPTION
**Pull request by Aliance**
Actualize docs after https://github.com/schmittjoh/serializer/pull/657

### CODE REVIEW

**Comment by Aliance** [comment]
Also, what do you think about adding alias to `double`: `float` & `real`?

**Comment by goetas** [comment]
Are they supported by php7 static tying?

**Comment by Aliance** [comment]
`float` – yes!
http://php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration.types

**Comment by goetas** [comment]
I'm fine for types supported by php7 then )

**Comment by Aliance** [comment]
Should I do in this pr or create a new one?

**Comment by goetas** [comment]
This should be fine :)

**Comment by Aliance** [comment]
Ok, I'll do that right after the weekend ;)

**Comment by goetas** [comment]
:+1:

**Comment by Aliance** [comment]
`float`  has already [supported](https://github.com/schmittjoh/serializer/commit/7724966e5f5c672b93ee1f128006318dda5a186d). So I will actualize docs & tests.

**Comment by goetas** [comment]
The changes to the tests now do not test "float" anymore... is it?

**Comment by Aliance** [comment]
There are 2 fixture with `double`: [Price](https://github.com/schmittjoh/serializer/blob/5ebae632eb79179c11a81f4ece77f086efdf493c/tests/JMS/Serializer/Tests/Fixtures/Price.php#L31) and [CurrencyAwarePrice](https://github.com/schmittjoh/serializer/blob/5ebae632eb79179c11a81f4ece77f086efdf493c/tests/JMS/Serializer/Tests/Fixtures/CurrencyAwarePrice.php#L34)& but I've found test only for price, which I was edited for `float` support. So the answer is – it seems that yes, there are no test for `double` now.

**Comment by goetas** [comment]
:+1:

**Comment by goetas** [comment]
rebased and merged with https://github.com/schmittjoh/serializer/commit/ce9f52474af714b58170a61f65a08964ef40c990

**Comment by Aliance** [comment]
Why don't you rebase this pr from github? :)

**Comment by goetas** [comment]
just habit to do it with console, running tests after merging. it is a double check that everything works.

sometimes i had troubles merging without checking the result, and do not want to have a not "green" master 

your commits are visible anyway https://github.com/schmittjoh/serializer/graphs/contributors?from=2016-08-14&to=2016-12-05&type=c

**Comment by Aliance** [comment]
But it loose one cool functionality: pr link near the comment
For example: https://github.com/schmittjoh/serializer/commits/master/.gitignore
If you click on commit hash, you saw the changes. But near the commit message there are no pr link. Sometimes it's a big need for it.

But never the less thanks for the review 👍

**Comment by goetas** [comment]
> But it loose one cool functionality: pr link near the comment

true. have not considered it. you right

ok, next time will ask to you to rebase :)

**Pull request closed without merging**
