### PR TITLE
Allow Post Serialize Event to overwrite existing data

### PR DESCRIPTION
**Pull request by jockri**
The GenericSerializationVisitor throws an exception when trying to add a data field that already exists. This PR makes it possible to change existing data for serialization purposes by adding the `replaceData ` method.

Solves issue: https://github.com/schmittjoh/serializer/issues/129

### CODE REVIEW

**Comment by jockri** [comment]
@schmittjoh Can you review this PR? Thx

**Comment by piotrantosik** [comment]
:+1:

**Comment by feastofvermin** [comment]
+1

**Comment by jockri** [comment]
@goetas I have merged the master branch again, so you can merge this PR.

**Comment by goetas** [comment]
@jockri tnx!

**Pull request merged**
