### PR TITLE
Recursion groups

### PR DESCRIPTION
**Pull request by Alexey-Stogny**

### CODE REVIEW

**Comment by goetas** [comment]
What is the usecase for this feature?

**Comment by goetas** [comment]
(And should be rebased on the current master, because many of the features you are introducing are already present(

**Comment by Alexey-Stogny** [comment]
@goetas sorry, it was my mistake to create pull request. I took @andreasferber idea, and modified to my needs. This changes give you ability to use only one top-level serialization group, and define nested entities groups in annotations.

**Comment by goetas** [comment]
:+1:

**Pull request closed without merging**
