### PR TITLE
[Feature] - Issue 424 - adding ExcludeForGroups 

### PR DESCRIPTION
**Pull request by leberknecht**
Adding functionality to exclude a property if a specifiy exclusion-group is set but expost it per default.
```php
    use JMS\Serializer\Annotation\ExcludeForGroups;

    class BlogPost
    {
        private $id;

        private $title;

        /** @ExcludeForGroups({"list"}) */
        private $comments;

        private $createdAt;
    }
```
If you now set the `list` exclusion-group on serialization, the `comments` property will be excluded::

    use JMS\Serializer\SerializationContext;

    $serializer->serialize(new BlogPost(), 'json', SerializationContext::create()->setExclusionGroups(array('list')));
    //will output $id, $title and $createdAt.

This can be handy if you just want to reduce your response without setting explicit groups for everything you want to expose.

### CODE REVIEW

**Comment by lotas** [comment]
:+1:

**Comment by smilesrg** [comment]
+1 for this feature

**Comment by afurculita** [comment]
@leberknecht how about replacing `@ExcludeForGroups({"list"})` with something like `@Exclude(groups={"list"})`? And adding a new type of ExclusionPolicy: maybe "GROUP"?

**Comment by leberknecht** [comment]
I like the idea! Atm the @Exclude is not handled as the other exclusion-policies, so maybe we should change that. Not sure if this will break BC....anyways => i think giving @exclude a group parameter solves my problem, i'll create a new PR for that :)

**Pull request closed without merging**
