### PR TITLE
#373 serializer fix

### PR DESCRIPTION
**Pull request by ttibensky**
https://github.com/schmittjoh/JMSSerializerBundle/issues/373

### CODE REVIEW

**Comment by smurfy** [comment]
Its quite an important fix, i had the problem that if one of my referenced objects is empty (all properties are null) the main array get converted to object.

This fix also fixes this problem.

**Comment by smartpierre** [comment]
Works like a charm ! Please merge !

@schmittjoh

**Comment by smartpierre** [comment]
Can we have a review ? @stof

**Comment by pommierw** [comment]
For my knowledge, can you tell me what's your version of PHP ?

Because, I have found that on my local machine, under PHP5.6, I have this problem, but on my staging server under PHP5.5, all seems to work... It's strange no ?

**Comment by nomack84** [comment]
:+1:

**Comment by dmatora** [comment]
:+1:

**Comment by ttibensky** [comment]
problem happening on PHP 5.5.9-1ubuntu4.11 (cli) (built: Jul  2 2015 15:23:08)

**Comment by plfort** [comment]
Any news about this PR ? @schmittjoh @stof 
Does it fix the problem without side effect ?

**Pull request closed without merging**
